/* =============================================================
 * Supabase 轻量同步层 CloudSync
 * 直接调用 Supabase REST（PostgREST），无需引入 supabase-js SDK。
 * 依赖：js/supabase-config.js（window.SUPABASE_CFG）
 *
 * 对应数据表（在 Supabase SQL Editor 中执行一次）：
 *   create table if not exists public.checkins (
 *     id bigint generated by default as identity primary key,
 *     cid text, name text not null, month text not null,
 *     data jsonb not null,
 *     created_at timestamptz default now()
 *   );
 *   alter table public.checkins enable row level security;
 *   create policy "checkins_insert" on public.checkins for insert to anon with check (true);
 *   create policy "checkins_select" on public.checkins for select to anon using (true);
 *
 *   客户档案备份表 cust_archive（第 46 轮：防止 localStorage 清理导致"数据隔天消失"）：
 *   create table if not exists public.cust_archive (
 *     id bigint generated by default as identity primary key,
 *     uid text not null unique,        -- 备份槽位，默认 'main'
 *     payload jsonb not null,          -- 全量客户档案快照 {v,at,customers:[...]}
 *     updated_at timestamptz default now()
 *   );
 *   alter table public.cust_archive enable row level security;
 *   create policy "ca_insert" on public.cust_archive for insert to anon with check (true);
 *   create policy "ca_select" on public.cust_archive for select to anon using (true);
 *   create policy "ca_update" on public.cust_archive for update to anon using (true) with check (true);
 * ============================================================= */
(function (global) {
  'use strict';

  function cfg() {
    var c = global.SUPABASE_CFG || {};
    return (c.url && c.anonKey) ? c : null;
  }
  function baseUrl() { return String(cfg().url).replace(/\/+$/, ''); }
  function headers() {
    return {
      'apikey': cfg().anonKey,
      'Authorization': 'Bearer ' + cfg().anonKey,
      'Content-Type': 'application/json'
    };
  }

  /* 上传一条打卡（data 为 checkin.html gather() 的完整对象） */
  function uploadCheckin(data) {
    return fetch(baseUrl() + '/rest/v1/checkins', {
      method: 'POST',
      headers: headers(),
      body: JSON.stringify({
        cid: data.cid || '',
        name: data.name || '',
        month: data.month || '',
        data: data
      })
    }).then(function (r) {
      if (!r.ok) throw new Error('云端上传失败（HTTP ' + r.status + '）');
      return true;
    });
  }

  /* 拉取某客户的云端打卡：优先 cid 匹配，同时兼容无 cid 时按姓名匹配。
     同一月多条（客户重复提交）取最新一条。 */
  function fetchCheckins(cid, name) {
    var or = [];
    if (cid) or.push('cid.eq.' + encodeURIComponent(cid));
    if (name) or.push('name.eq.' + encodeURIComponent(name));
    var q = baseUrl() + '/rest/v1/checkins?select=id,cid,name,month,data,created_at&order=created_at.desc&limit=200';
    if (or.length) q += '&or=(' + or.join(',') + ')';
    return fetch(q, { headers: headers() }).then(function (r) {
      if (!r.ok) throw new Error('云端拉取失败（HTTP ' + r.status + '）');
      return r.json();
    }).then(function (rows) {
      var byMonth = {};
      rows.forEach(function (row) {
        var m = row.month || (row.data && row.data.month);
        if (m && !byMonth[m]) byMonth[m] = row;   // 已按 created_at 降序，首个即最新
      });
      return Object.keys(byMonth).map(function (m) { return byMonth[m]; });
    });
  }

  /* 拉取云端全部打卡记录（不限客户，供「云端记录」总览/手动导入使用） */
  function fetchAllCheckins() {
    return fetch(baseUrl() + '/rest/v1/checkins?select=id,cid,name,month,data,created_at&order=created_at.desc&limit=1000', { headers: headers() })
      .then(function (r) { if (!r.ok) throw new Error('云端拉取失败（HTTP ' + r.status + '）'); return r.json(); });
  }

  /* 连通性测试：读取表 1 行（配置正确且表已建好时返回 true） */
  function ping() {
    return fetch(baseUrl() + '/rest/v1/checkins?select=id&limit=1', { headers: headers() })
      .then(function (r) { if (!r.ok) throw new Error('HTTP ' + r.status); return true; });
  }

  /* ---------------- 客户档案云端备份（防止本地存储被清理丢档） ----------------
     备份槽位 upsert：整份 {customers:[...]} 快照覆盖写入 uid 行。
     PostgREST on_conflict=uid + resolution=merge-duplicates 实现「有则更新、无则插入」。 */
  function backupCustomers(payload, uid) {
    var key = uid || 'main';
    var h = headers();
    h['Prefer'] = 'resolution=merge-duplicates';
    return fetch(baseUrl() + '/rest/v1/cust_archive?on_conflict=uid', {
      method: 'POST',
      headers: h,
      body: JSON.stringify({ uid: key, payload: payload })
    }).then(function (r) {
      if (!r.ok) throw new Error('云端备份失败（HTTP ' + r.status + '）');
      return true;
    });
  }

  /* 读取某槽位的备份快照；本地无备份记录时返回 null */
  function fetchCustomersBackup(uid) {
    var key = uid || 'main';
    return fetch(baseUrl() + '/rest/v1/cust_archive?uid=eq.' + encodeURIComponent(key) + '&select=payload,updated_at&limit=1', { headers: headers() })
      .then(function (r) {
        if (!r.ok) throw new Error('云端读取备份失败（HTTP ' + r.status + '）');
        return r.json();
      })
      .then(function (rows) {
        if (!rows || !rows.length) return null;
        return { payload: rows[0].payload || null, at: rows[0].updated_at || '' };
      });
  }

  /* 备份表是否已就绪（用户尚未在 SQL Editor 执行 cust_archive 建表语句时返回 false） */
  function backupTableReady() {
    return fetch(baseUrl() + '/rest/v1/cust_archive?select=uid&limit=1', { headers: headers() })
      .then(function (r) { return r.ok; })
      .catch(function () { return false; });
  }

  global.CloudSync = {
    ready: function () { return !!cfg(); },
    config: cfg,
    uploadCheckin: uploadCheckin,
    fetchCheckins: fetchCheckins,
    fetchAllCheckins: fetchAllCheckins,
    ping: ping,
    backupCustomers: backupCustomers,
    fetchCustomersBackup: fetchCustomersBackup,
    backupTableReady: backupTableReady
  };
})(window);
